name: Tests

on: [push]

env:
  DB_CONNECTION: mysql
  DB_DATABASE: dda_builds
  DB_PORT: 33306
  DB_USER: root
  DB_PASSWORD: rootPassword
  APP_ENV: testing

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootPassword
          MYSQL_DATABASE: dda_builds
        # map the "external" 33306 port with the "internal" 3306
        ports:
          - 33306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache - NPM dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache - Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: imagick, gd

      - name: Composer - Install dependencies
        run: composer install -n --prefer-dist --no-progress
        env:
          APP_ENV: testing

      - name: Laravel - Prepare
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan migrate:fresh

      - name: NPM - Install Dependencies
        run: npm install

      - name: NPM - Build
        run: npm run build

      - name: Run ESLint
        run: npm run eslint

      - name: Laravel - Start Application
        run: |
          php artisan dusk:chrome-driver --detect
          chmod -R 0755 public/
          mkdir storage/app/public/thumbnails
          chmod -R 0755 storage/
          chmod -R 0755 vendor/laravel/dusk/bin/
          ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
          php artisan serve > /dev/null 2>&1 &

      - name: Tests - PHPUnit
        run: ./vendor/bin/phpunit

      - name: Tests - Dusk (Browser Tests)
        run: php artisan dusk

      - name: Tests - NPM Build
        run: npm run build

      - name: Upload artifacts - Laravel Logs
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./storage/logs

      - name: Upload artifacts - Browser Screenshots
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Browser Screenshots
          path: ./tests/Browser/screenshots